force-app/main/default/objects/Order_c__c/Order_c__c.object-meta.xml
<CustomObject>
    <label>Order__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_c__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>TotalPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_c__c/fields/TotalProductCount__c.field-meta.xml
<CustomField>
    <fullName>TotalProductCount__c</fullName>
    <label>TotalProductCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderDataManagerTest.cls
@IsTest
public with sharing class OrderDataManagerTest {
    
    @IsTest
    public static void testGetOrderMap() {
        Account account = TestUtils.createAccount();
        insert account;
        Order_c__c order = TestUtils.createOrder(account.Id);
        insert order;

        Map<Id, Order_c__c> orderMap = OrderDataManager.getOrderMap(new Set<Id>{order.Id});
        Order_c__c data = orderMap.get(order.Id);
        System.assertEquals(order.TotalPrice__c, data.TotalPrice__c);
        System.assertEquals(order.TotalProductCount__c, data.TotalProductCount__c);
    }

}