force-app/main/default/objects/Order_c__c/Order_c__c.object-meta.xml
<CustomObject>
    <label>Order__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_c__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>TotalPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_c__c/fields/TotalProductCount__c.field-meta.xml
<CustomField>
    <fullName>TotalProductCount__c</fullName>
    <label>TotalProductCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem_c__c/OrderItem_c__c.object-meta.xml
<CustomObject>
    <label>OrderItem__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem_c__c/fields/Order_c__c.field-meta.xml
<CustomField>
    <fullName>Order_c__c</fullName>
    <label>Order__c</label>
    <referenceTo>Order_c__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderItemHandler.cls
public with sharing class OrderItemHandler {
    
    public static Set<Id> getOrderIds(List<OrderItem_c__c> orderItems) {
        Set<Id> orderIds = new Set<Id>();
        for (OrderItem_c__c item : orderItems) {
            orderIds.add(item.Order_c__c);
        }
        return orderIds;
    }

    public static void handleOrder(List<OrderItem_c__c> orderItems) {
        Set<Id> orderIds = OrderItemHandler.getOrderIds(orderItems);
        Map<Id, Order_c__c> orderMap = OrderDataManager.getOrderMap(orderIds);
        for (OrderItem_c__c item : orderItems) {
            Order_c__c order = orderMap.get(item.Order_c__c);
            order.TotalProductCount__c += item.Quantity__c;
            order.TotalPrice__c += item.Price__c * item.Quantity__c;
        }
        update orderMap.values();
    }

}