force-app/main/default/objects/Order_c__c/Order_c__c.object-meta.xml
<CustomObject>
    <label>Order__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_c__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>TotalPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_c__c/fields/TotalProductCount__c.field-meta.xml
<CustomField>
    <fullName>TotalProductCount__c</fullName>
    <label>TotalProductCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem_c__c/OrderItem_c__c.object-meta.xml
<CustomObject>
    <label>OrderItem__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem_c__c/fields/Order_c__c.field-meta.xml
<CustomField>
    <fullName>Order_c__c</fullName>
    <label>Order__c</label>
    <referenceTo>Order_c__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem_c__c/fields/Product_c__c.field-meta.xml
<CustomField>
    <fullName>Product_c__c</fullName>
    <label>Product__c</label>
    <referenceTo>Product_c__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_c__c/Product_c__c.object-meta.xml
<CustomObject>
    <label>Product__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_c__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family 1</fullName>
            </value>
            <value>
                <fullName>Family 2</fullName>
            </value>
            <value>
                <fullName>Family 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_c__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Type 1</fullName>
            </value>
            <value>
                <fullName>Type 2</fullName>
            </value>
            <value>
                <fullName>Type 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUtils.cls
public with sharing class TestUtils {
    
    public static Account createAccount() {
        Account account = new Account(
            Name = 'test',
            AccountNumber = '2342342'
        );
        return account;
    }

    public static Order_c__c createOrder(Id accountId) {
        Order_c__c order = new Order_c__c(
            Account__c = accountId,
            TotalProductCount__c = 1, 
            TotalPrice__c = 100
        );
        return order;
    }

    public static List<Product_c__c> createProducts() {
        List<Product_c__c> testData = new List<Product_c__c>{
            new Product_c__c(
                Name = 'name 1',
                Description__c = 'desc 1',
                Type__c = 'Type 1',
                Family__c = 'Family 1', 
                Price__c = 100
            ),
            new Product_c__c(
                Name = 'name 2',
                Description__c = 'desc 2',
                Type__c = 'Type 2',
                Family__c = 'Family 2',
                Price__c = 200
            ),
            new Product_c__c(
                Name = 'name 3',
                Description__c = 'desc 3',
                Type__c = 'Type 3',
                Family__c = 'Family 3',
                Price__c = 500
            )
        };
        return testData;
    }

    public static OrderItem_c__c createOrderItem(Id orderId, Product_c__c product) {
        return new OrderItem_c__c(
            Order_c__c = orderId,
            Product_c__c = product.Id,
            Quantity__c = 1,
            Price__c = product.Price__c
        );
    }
}