force-app/main/default/objects/Product_c__c/Product_c__c.object-meta.xml
<CustomObject>
    <label>Product__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_c__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family 1</fullName>
            </value>
            <value>
                <fullName>Family 2</fullName>
            </value>
            <value>
                <fullName>Family 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_c__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Type 1</fullName>
            </value>
            <value>
                <fullName>Type 2</fullName>
            </value>
            <value>
                <fullName>Type 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductDataManager.cls
public with sharing class ProductDataManager {
    
    public static List<Product_c__c> getProducts(String name, List<String> types , List<String> families) {
        if (name == null) {
            return null;
        } else {
            String nameKey = '%' + name + '%';
            System.debug(types);
            System.debug(families);
            return ([
                SELECT Id, Name, Description__c, Type__c, Family__c
                FROM Product_c__c
                WHERE Name LIKE :nameKey
                AND Family__c IN :families
                AND Type__c IN :types
            ]);
        }
    }

    public static List<Product_c__c> getProducts(Set<Id> ids) {
        return ([
                SELECT Id, Price__c
                FROM Product_c__c
                WHERE Id IN :ids
            ]);
    }

}